In [1]:
import os
from pathlib import Path

import pandas as pd

# Configure pandas to show all columns and data without truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
import time


def get_env_value(key, default=None, env_path=".env"):
    # Prefer shell variables first, then fall back to the local .env file so the notebook works in VS Code and headless runs.
    value = os.getenv(key)
    if value:
        return value

    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as env_file:
            for line in env_file:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                name, raw_value = line.split("=", 1)
                if name.strip() == key:
                    return raw_value.strip().strip('"').strip("'")
    return default


def get_env_int(key, default):
    return int(get_env_value(key, str(default)))


def get_env_float(key, default):
    return float(get_env_value(key, str(default)))


# Keep the notebook data paths configurable so the same code works across local machines and test setups.
csv_path = Path(get_env_value("CSV_PATH", "IOT Data Simulation/smart_logistic_tracker_japan.csv"))
sample_rows = get_env_int("SAMPLE_ROWS", 5)
write_delay_seconds = get_env_float("WRITE_DELAY_SECONDS", 0.1)
write_gas_limit = get_env_int("WRITE_GAS_LIMIT", 3000000)
enable_duplicate_writes = get_env_value("ENABLE_DUPLICATE_WRITES", "false").lower() in {"1", "true", "yes", "on"}
abi_path = Path(get_env_value("ABI_PATH", "contracts/abi.json"))

# Load the CSV file with basic error handling
try:
    df = pd.read_csv(csv_path)
    print(f"Total records in CSV: {len(df)}")
    print(f"First {sample_rows} records:")

    # Display the first few rows
    display(df.head(sample_rows))
except FileNotFoundError:
    print(f"❌ CSV file not found: {csv_path}")
    df = pd.DataFrame()
except pd.errors.EmptyDataError:
    print(f"❌ CSV file is empty: {csv_path}")
    df = pd.DataFrame()
except pd.errors.ParserError as error:
    print(f"❌ Failed to parse CSV file {csv_path}: {error}")
    df = pd.DataFrame()
except Exception as error:
    print(f"❌ Unexpected error while loading {csv_path}: {error}")
    df = pd.DataFrame()

Total records in CSV: 100
First 5 records:

                    timestamp           carrier  tracking_number package_id   origin             current_location delivery_location prefecture   latitude   longitude                      latest_status logistics_delay_reason  logistics_delay                  order_date      expected_delivery_date  waiting_time_minutes perishable  temperature  humidity    rfid_tag  rfid_verified tamper_alert traffic_status  inventory_level  asset_utilization
0  2026-05-04 13:50:26.857905  Yamato Transport     942646961460    PKG7545    Tokyo     Naha Central Post Office             Tokyo   Kanagawa  35.993159  139.038781                   Out for Delivery                    NaN                0  2026-04-29 23:26:26.858009  2026-05-05 23:26:26.858015                    45         No         10.7        40  RFID736892          False           No          Heavy               99              84.59
1  2026-05-03 23:36:26.858095        Japan Post      74355111775    PKG2659    Tokyo   Nagoya Central Post Office             Kyoto   Kanagawa  35.691292  139.130870                            Arrival                    NaN                0  2026-04-28 23:26:26.858141  2026-05-07 23:26:26.858146                    54        Yes          6.2        82  RFID156229          False          Yes         Detour              363              53.39
2  2026-05-04 08:32:26.858217        Japan Post     217497030475    PKG7965    Osaka   Nagoya Central Post Office             Osaka      Aichi  35.591109  139.784940                            Storage                    NaN                1  2026-05-03 23:26:26.858267  2026-05-08 23:26:26.858271                   144        Yes         -3.1        86  RFID890703           True          Yes          Heavy               25              95.75
3  2026-05-04 02:35:26.858332        Japan Post     249781996688    PKG5296  Fukuoka  Sapporo Central Post Office           Sapporo      Osaka  35.570440  139.689163  Delivered to the delivery address                    NaN                0  2026-05-03 23:26:26.858370  2026-05-05 23:26:26.858374                   173        Yes          6.3        87  RFID603182           True          Yes         Detour              145              63.84
4  2026-05-04 08:28:26.858444        Japan Post     718415724062    PKG9987  Fukuoka        Yokohama Sales Office           Sapporo   Hokkaido  35.679375  139.408071  Bring it back due to your absence        Address Unknown                1  2026-05-03 23:26:26.858492  2026-05-07 23:26:26.858501                    82         No          0.7        60  RFID921432          False          Yes         Detour               34              56.28

In [2]:
from web3 import Web3

# Connect to local blockchain
ganache_url = get_env_value("GANACHE_URL", "http://127.0.0.1:8545")
web3 = Web3(Web3.HTTPProvider(ganache_url))

# Verify connection
if web3.is_connected():
    print("✅ Connected to Ganache successfully!")
else:
    print("❌ Connection failed. Ensure Ganache is running.")

✅ Connected to Ganache successfully!

In [3]:
import json

# Use the loaded ABI path and deployed contract address.
contract_address = get_env_value("CONTRACT_ADDRESS")
if not contract_address:
    raise ValueError("CONTRACT_ADDRESS is missing. Set it in .env or the environment.")
contract_address = Web3.to_checksum_address(contract_address)

# Load the ABI that matches the deployed contract in this repository.
with open(abi_path, "r", encoding="utf-8") as abi_file:
    abi = json.load(abi_file)

# Load the smart contract.
contract = web3.eth.contract(address=contract_address, abi=abi)

# Ganache may expose a different unlocked account set than the deployed contract owner,
# so we fall back to an explicit override when needed.
contract_owner = contract.functions.owner().call()
if contract_owner not in web3.eth.accounts:
    override_owner = get_env_value("CONTRACT_OWNER")
    if not override_owner:
        raise ValueError(
            f"Contract owner {contract_owner} is not unlocked in Ganache. "
            "Set CONTRACT_OWNER in .env to an unlocked account."
        )
    contract_owner = Web3.to_checksum_address(override_owner)
    if contract_owner not in web3.eth.accounts:
        raise ValueError(
            f"CONTRACT_OWNER {contract_owner} is not unlocked in Ganache."
        )

web3.eth.default_account = contract_owner

print(f"✅ Connected to Smart Contract at {contract_address}")
print(f"✅ Using sender account: {web3.eth.default_account}")

✅ Connected to Smart Contract at 0x3c64Bb4df9DC16b57D62B281bd56742060CF78Ee
✅ Using sender account: 0x384F585463b9D2288A637615e1576E4F3798B073

In [4]:
# Retrieve all existing records from the blockchain once at startup to cache them.
# This prevents expensive O(N) blockchain roundtrips for duplicate verification on every iteration.
total_records = contract.functions.getTotalRecords().call()
existing_records = set()
for record_index in range(total_records):
    record = contract.functions.getRecord(record_index).call()
    existing_records.add((str(record[1]), str(record[2]), str(record[3])))

def record_exists(package_id, data_type, data_value):
    """Return True when the exact record is already in the cache."""
    return (str(package_id), str(data_type), str(data_value)) in existing_records


def send_iot_data(package_id, data_type, data_value):
    """
    Sends logistics IoT data
    to the deployed smart contract
    """

    # Skip exact duplicates unless testing explicitly requires them.
    if not enable_duplicate_writes and record_exists(package_id, data_type, data_value):
        print(
            f"ℹ️ Skipped duplicate | {package_id} | "
            f"Type: {data_type} | Value: {data_value}"
        )
        return False

    if enable_duplicate_writes:
        print("ℹ️ Duplicate-write mode is ON; exact duplicates will be stored.")

    txn = contract.functions.storeData(
        package_id,
        data_type,
        data_value
    ).transact({
        'from': web3.eth.default_account,
        'gas': write_gas_limit
    })

    # Wait for transaction confirmation before moving to the next record.
    receipt = web3.eth.wait_for_transaction_receipt(txn)

    # Cache the new entry locally
    existing_records.add((str(package_id), str(data_type), str(data_value)))

    print(
        f"✅ Data Stored | {package_id} | "
        f"Type: {data_type} | "
        f"Value: {data_value} | "
        f"Txn Hash: {receipt.transactionHash.hex()}"
    )
    return True

# Each CSV row writes multiple contract entries depending on the columns.
is_iot_data = "shipment_id" in df.columns
entries_per_row = 3 if is_iot_data else 4

target_contract_records = int(get_env_value("TARGET_CONTRACT_RECORDS", "100"))
target_rows = target_contract_records // entries_per_row
current_records = contract.functions.getTotalRecords().call()
max_entries = contract.functions.MAX_ENTRIES().call()
remaining_entries = max_entries - current_records
rows_to_store = min(len(df), target_rows, remaining_entries // entries_per_row)

print(f"Target contract records: {target_contract_records}")
print(f"Current records: {current_records}")
print(f"Maximum records: {max_entries}")
print(f"Remaining contract slots: {remaining_entries}")
print(f"Rows that can still be stored safely: {rows_to_store}")
print(f"Duplicate writes enabled: {enable_duplicate_writes}")

if target_contract_records % entries_per_row != 0:
    print(f"⚠️ TARGET_CONTRACT_RECORDS is not a multiple of {entries_per_row}, ignoring remaining slots to keep rows complete.")

if rows_to_store <= 0:
    print("⚠️ No remaining storage capacity on the contract.")
else:
    stored_rows = 0
    skipped_rows = 0

    for index, row in df.head(rows_to_store).iterrows():
        if is_iot_data:
            package_id = str(row["shipment_id"])
            status = str(row["shipment_status"])
            temp = f"{row['temperature']}°C"
            humid = f"{row['humidity']}%"

            s1 = send_iot_data(package_id, "Status", status)
            s2 = send_iot_data(package_id, "Temperature", temp)
            s3 = send_iot_data(package_id, "Humidity", humid)

            if s1 or s2 or s3:
                stored_rows += 1
            else:
                skipped_rows += 1
        else:
            package_id = str(row["package_id"])
            location = str(row["current_location"])
            status = str(row["latest_status"])
            temp = f"{row['temperature']}°C"
            humid = f"{row['humidity']}%"

            s1 = send_iot_data(package_id, "Location", location)
            s2 = send_iot_data(package_id, "Status", status)
            s3 = send_iot_data(package_id, "Temperature", temp)
            s4 = send_iot_data(package_id, "Humidity", humid)

            if s1 or s2 or s3 or s4:
                stored_rows += 1
            else:
                skipped_rows += 1

        # Small pause between transactions keeps Ganache logs readable and avoids flooding the provider.
        time.sleep(write_delay_seconds)

    print(f"\n✅ Successfully stored {stored_rows} new rows on the blockchain!")
    if skipped_rows:
        print(f"ℹ️ Skipped {skipped_rows} duplicate rows.")

Target contract records: 400
Current records: 100
Maximum records: 500
Remaining contract slots: 400
Rows that can still be stored safely: 100
Duplicate writes enabled: False
ℹ️ Skipped duplicate | PKG7545 | Type: Location | Value: Naha Central Post Office
ℹ️ Skipped duplicate | PKG7545 | Type: Status | Value: Out for Delivery
ℹ️ Skipped duplicate | PKG7545 | Type: Temperature | Value: 10.7°C
ℹ️ Skipped duplicate | PKG7545 | Type: Humidity | Value: 40%
ℹ️ Skipped duplicate | PKG2659 | Type: Location | Value: Nagoya Central Post Office
ℹ️ Skipped duplicate | PKG2659 | Type: Status | Value: Arrival
ℹ️ Skipped duplicate | PKG2659 | Type: Temperature | Value: 6.2°C
ℹ️ Skipped duplicate | PKG2659 | Type: Humidity | Value: 82%

ℹ️ Skipped duplicate | PKG7965 | Type: Location | Value: Nagoya Central Post Office
ℹ️ Skipped duplicate | PKG7965 | Type: Status | Value: Storage
ℹ️ Skipped duplicate | PKG7965 | Type: Temperature | Value: -3.1°C
ℹ️ Skipped duplicate | PKG7965 | Type: Humidity | Value: 86%
ℹ️ Skipped duplicate | PKG5296 | Type: Location | Value: Sapporo Central Post Office
ℹ️ Skipped duplicate | PKG5296 | Type: Status | Value: Delivered to the delivery address
ℹ️ Skipped duplicate | PKG5296 | Type: Temperature | Value: 6.3°C
ℹ️ Skipped duplicate | PKG5296 | Type: Humidity | Value: 87%

ℹ️ Skipped duplicate | PKG9987 | Type: Location | Value: Yokohama Sales Office
ℹ️ Skipped duplicate | PKG9987 | Type: Status | Value: Bring it back due to your absence
ℹ️ Skipped duplicate | PKG9987 | Type: Temperature | Value: 0.7°C
ℹ️ Skipped duplicate | PKG9987 | Type: Humidity | Value: 60%
ℹ️ Skipped duplicate | PKG8392 | Type: Location | Value: Nagoya Central Post Office
ℹ️ Skipped duplicate | PKG8392 | Type: Status | Value: Hold at Yamato
ℹ️ Skipped duplicate | PKG8392 | Type: Temperature | Value: 2.5°C
ℹ️ Skipped duplicate | PKG8392 | Type: Humidity | Value: 61%

ℹ️ Skipped duplicate | PKG2808 | Type: Location | Value: Naha Central Post Office
ℹ️ Skipped duplicate | PKG2808 | Type: Status | Value: Delay
ℹ️ Skipped duplicate | PKG2808 | Type: Temperature | Value: 0.9°C
ℹ️ Skipped duplicate | PKG2808 | Type: Humidity | Value: 48%
ℹ️ Skipped duplicate | PKG1749 | Type: Location | Value: Fukuoka Distribution Center
ℹ️ Skipped duplicate | PKG1749 | Type: Status | Value: Arrival
ℹ️ Skipped duplicate | PKG1749 | Type: Temperature | Value: 19.6°C
ℹ️ Skipped duplicate | PKG1749 | Type: Humidity | Value: 34%

ℹ️ Skipped duplicate | PKG1803 | Type: Location | Value: Sapporo Central Post Office
ℹ️ Skipped duplicate | PKG1803 | Type: Status | Value: Hand it over at the window
ℹ️ Skipped duplicate | PKG1803 | Type: Temperature | Value: 22.6°C
ℹ️ Skipped duplicate | PKG1803 | Type: Humidity | Value: 55%
ℹ️ Skipped duplicate | PKG2151 | Type: Location | Value: Yokohama Sales Office
ℹ️ Skipped duplicate | PKG2151 | Type: Status | Value: In Transit
ℹ️ Skipped duplicate | PKG2151 | Type: Temperature | Value: 23.0°C
ℹ️ Skipped duplicate | PKG2151 | Type: Humidity | Value: 89%

ℹ️ Skipped duplicate | PKG2585 | Type: Location | Value: Yokohama Sales Office
ℹ️ Skipped duplicate | PKG2585 | Type: Status | Value: Arrival Scan
ℹ️ Skipped duplicate | PKG2585 | Type: Temperature | Value: 8.3°C
ℹ️ Skipped duplicate | PKG2585 | Type: Humidity | Value: 73%
ℹ️ Skipped duplicate | PKG7157 | Type: Location | Value: Yokohama Sales Office
ℹ️ Skipped duplicate | PKG7157 | Type: Status | Value: Hand it over at the window
ℹ️ Skipped duplicate | PKG7157 | Type: Temperature | Value: 1.0°C
ℹ️ Skipped duplicate | PKG7157 | Type: Humidity | Value: 51%

ℹ️ Skipped duplicate | PKG5612 | Type: Location | Value: Naha Central Post Office
ℹ️ Skipped duplicate | PKG5612 | Type: Status | Value: Bring it back due to your absence
ℹ️ Skipped duplicate | PKG5612 | Type: Temperature | Value: 4.4°C
ℹ️ Skipped duplicate | PKG5612 | Type: Humidity | Value: 48%
ℹ️ Skipped duplicate | PKG2377 | Type: Location | Value: Osaka Central Post Office
ℹ️ Skipped duplicate | PKG2377 | Type: Status | Value: Returned
ℹ️ Skipped duplicate | PKG2377 | Type: Temperature | Value: 9.4°C
ℹ️ Skipped duplicate | PKG2377 | Type: Humidity | Value: 81%

ℹ️ Skipped duplicate | PKG3244 | Type: Location | Value: Fukuoka Distribution Center
ℹ️ Skipped duplicate | PKG3244 | Type: Status | Value: Returned
ℹ️ Skipped duplicate | PKG3244 | Type: Temperature | Value: 2.0°C
ℹ️ Skipped duplicate | PKG3244 | Type: Humidity | Value: 60%
ℹ️ Skipped duplicate | PKG4196 | Type: Location | Value: Naha Central Post Office
ℹ️ Skipped duplicate | PKG4196 | Type: Status | Value: Storage
ℹ️ Skipped duplicate | PKG4196 | Type: Temperature | Value: 14.5°C
ℹ️ Skipped duplicate | PKG4196 | Type: Humidity | Value: 62%

ℹ️ Skipped duplicate | PKG8850 | Type: Location | Value: Nagoya Central Post Office
ℹ️ Skipped duplicate | PKG8850 | Type: Status | Value: Delivered
ℹ️ Skipped duplicate | PKG8850 | Type: Temperature | Value: 11.1°C
ℹ️ Skipped duplicate | PKG8850 | Type: Humidity | Value: 51%
ℹ️ Skipped duplicate | PKG8659 | Type: Location | Value: Fukuoka Distribution Center
ℹ️ Skipped duplicate | PKG8659 | Type: Status | Value: Hold at Yamato
ℹ️ Skipped duplicate | PKG8659 | Type: Temperature | Value: 21.1°C
ℹ️ Skipped duplicate | PKG8659 | Type: Humidity | Value: 88%

ℹ️ Skipped duplicate | PKG1347 | Type: Location | Value: Nagoya Central Post Office
ℹ️ Skipped duplicate | PKG1347 | Type: Status | Value: Returned to the sender
ℹ️ Skipped duplicate | PKG1347 | Type: Temperature | Value: 18.8°C
ℹ️ Skipped duplicate | PKG1347 | Type: Humidity | Value: 76%
ℹ️ Skipped duplicate | PKG8088 | Type: Location | Value: Tokyo Central Post Office
ℹ️ Skipped duplicate | PKG8088 | Type: Status | Value: Under Investigation
ℹ️ Skipped duplicate | PKG8088 | Type: Temperature | Value: 8.7°C
ℹ️ Skipped duplicate | PKG8088 | Type: Humidity | Value: 37%

ℹ️ Skipped duplicate | PKG2762 | Type: Location | Value: Yokohama Sales Office
ℹ️ Skipped duplicate | PKG2762 | Type: Status | Value: Arrival Scan
ℹ️ Skipped duplicate | PKG2762 | Type: Temperature | Value: -2.5°C
ℹ️ Skipped duplicate | PKG2762 | Type: Humidity | Value: 77%
ℹ️ Skipped duplicate | PKG8577 | Type: Location | Value: Naha Central Post Office
ℹ️ Skipped duplicate | PKG8577 | Type: Status | Value: Hand it over at the window
ℹ️ Skipped duplicate | PKG8577 | Type: Temperature | Value: 0.7°C
ℹ️ Skipped duplicate | PKG8577 | Type: Humidity | Value: 36%

ℹ️ Skipped duplicate | PKG5517 | Type: Location | Value: Yokohama Sales Office
ℹ️ Skipped duplicate | PKG5517 | Type: Status | Value: Delay
ℹ️ Skipped duplicate | PKG5517 | Type: Temperature | Value: -2.4°C
ℹ️ Skipped duplicate | PKG5517 | Type: Humidity | Value: 85%
ℹ️ Skipped duplicate | PKG7409 | Type: Location | Value: Sapporo Central Post Office
ℹ️ Skipped duplicate | PKG7409 | Type: Status | Value: Arrival
ℹ️ Skipped duplicate | PKG7409 | Type: Temperature | Value: 2.3°C
ℹ️ Skipped duplicate | PKG7409 | Type: Humidity | Value: 65%

ℹ️ Skipped duplicate | PKG5985 | Type: Location | Value: Tokyo Central Post Office
ℹ️ Skipped duplicate | PKG5985 | Type: Status | Value: Returned
ℹ️ Skipped duplicate | PKG5985 | Type: Temperature | Value: 4.3°C
ℹ️ Skipped duplicate | PKG5985 | Type: Humidity | Value: 61%

✅ Data Stored | PKG2775 | Type: Location | Value: Osaka Central Post Office | Txn Hash: 1922134e5dca6035a5a7e830b2674280f4af495a5e50a45a8fe5beea5498f9f0
✅ Data Stored | PKG2775 | Type: Status | Value: Under Investigation | Txn Hash: 495dde675bfaaad2082fac0d729a35b035c134058e3bbe3a08fd7aed92d88c7f

✅ Data Stored | PKG2775 | Type: Temperature | Value: 3.2°C | Txn Hash: 7c883be1095918b024c770843b50dff37e5e97513a5447317980b21c2fb388fe
✅ Data Stored | PKG2775 | Type: Humidity | Value: 61% | Txn Hash: 0848b10351f41fd1f4be8b3051fbbc6bed0dfbe73aaa0c2ee73f51ed933447cf

✅ Data Stored | PKG2220 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: c459254eb9ba8696191d437a6b2ef33eff4597dfe0d4217373ad76eb357f94c6
✅ Data Stored | PKG2220 | Type: Status | Value: Delivered to the delivery address | Txn Hash: ae822d241c7afd414ded7f63bef6b2797e56001e816ee10ff91a4db4372e6aa6

✅ Data Stored | PKG2220 | Type: Temperature | Value: 14.2°C | Txn Hash: 2805d90a975f3c10aab9439ab2fc29656630474f8ac0cd338493f94b91802b55
✅ Data Stored | PKG2220 | Type: Humidity | Value: 85% | Txn Hash: 9d075277e7ea1c69fd7d65a2bf86de3714544fe5318426494d5bf44ee7123cf6

✅ Data Stored | PKG1643 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: b1f86332706241a9cb7e86a3474001e6845c34b601bf3ce24161fdcefba2d259
✅ Data Stored | PKG1643 | Type: Status | Value: Arrival | Txn Hash: c88c2e328fee4176878cadd7d34690fd8056ab0ba2ae0d91a605e10df0fa3fbd
✅ Data Stored | PKG1643 | Type: Temperature | Value: 14.8°C | Txn Hash: 05ca275d874bb82c381a1ae8983fc79bab9afb9ce76747d52de05d58fba3c86a

✅ Data Stored | PKG1643 | Type: Humidity | Value: 74% | Txn Hash: af0a34aab44aec68b7816c31551a5c85af3206359a62c9b9f2707ea99b4ca21a

✅ Data Stored | PKG9122 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: 9e68168a344ccbe708c4567a3a609cb3c13073b343154128456e19691bec4a9d
✅ Data Stored | PKG9122 | Type: Status | Value: Delay | Txn Hash: f12b8888902afcb999e4d69e898d955ff5b011750d1dfa26d4909eb5568dfa92
✅ Data Stored | PKG9122 | Type: Temperature | Value: 22.3°C | Txn Hash: 6755acd23435deb110456de117302d2213951394de9a456000db4f6e8247de4d

✅ Data Stored | PKG9122 | Type: Humidity | Value: 47% | Txn Hash: 7e1059dcd5a81c7c6eafc75b65cdef76947375e53742b6954788620d566b512e
✅ Data Stored | PKG6691 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 2b49c86eb413dff153e285d3f0ad6a7683a497b2320aaea0b2ebc930924d7699

✅ Data Stored | PKG6691 | Type: Status | Value: Bring it back due to your absence | Txn Hash: f8558cf95b3654745ce887e76851778ce7bcc70d1686e351a42bdf08c32dcfd2
✅ Data Stored | PKG6691 | Type: Temperature | Value: 11.6°C | Txn Hash: b77b731e05d2175a0a840c72710eeb08771c8eb7b8a7a3cd398d94859c993d89
✅ Data Stored | PKG6691 | Type: Humidity | Value: 61% | Txn Hash: ab503f4de25cddf7da69ae763da3eab13b610ea93d2f2d1ca94ebc0b194a6b7b

✅ Data Stored | PKG7202 | Type: Location | Value: Osaka Central Post Office | Txn Hash: c4ca224ce7defe0e32f71a9e4eaf36378fe52147aacf0d6295bab00895ff1928
✅ Data Stored | PKG7202 | Type: Status | Value: Arrival Scan | Txn Hash: f4f6c3012fc116f287b5cdacf82c571ec84f0ad69a59f783161a624c5743807e
✅ Data Stored | PKG7202 | Type: Temperature | Value: 3.7°C | Txn Hash: 6e6cb842805925e2cff5091b5121597555bf94876165af72204e77a8e73ddfc3

✅ Data Stored | PKG7202 | Type: Humidity | Value: 47% | Txn Hash: 105c9b71f55007d17931547f9ca75c52646855c5a2b7055445758fd3bdbdabe1
✅ Data Stored | PKG3751 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 608fe4996f00746b9ce2fb3f9c8e0b4760550cacc5f2e35a035ac208b9b0ad8f

✅ Data Stored | PKG3751 | Type: Status | Value: Departure Scan | Txn Hash: 26ea55498f425f39b5b0e0d8285bb6179b0d671dd0be9b23692a5249d927f2e7
✅ Data Stored | PKG3751 | Type: Temperature | Value: 16.3°C | Txn Hash: 37b2206c0c92e4758a48a9c4592245eb2d20c915167a5f1fb762f35a8345451c
✅ Data Stored | PKG3751 | Type: Humidity | Value: 76% | Txn Hash: 054f7c6bee8a175f9916b81860137e3859fb5d61182617399e56ee6e45de6993

✅ Data Stored | PKG2956 | Type: Location | Value: Naha Central Post Office | Txn Hash: 89457b569988aa7a8d96edc99b488c07d49d3f46e64567ab95a06d5e4338f435
✅ Data Stored | PKG2956 | Type: Status | Value: Returned | Txn Hash: 1b87b3dbb09edd9e4c529f5089dec6976e7e2a4079a751ab4b9bcf2b84c74d07
✅ Data Stored | PKG2956 | Type: Temperature | Value: 22.2°C | Txn Hash: 139e21b91de0c6ebaffcb472fc1f1e4c62953391648e8c1e96bec924b9aed53a
✅ Data Stored | PKG2956 | Type: Humidity | Value: 82% | Txn Hash: dd7fc363b57a0eec019854a01edba3f219c0753263b48b92fb6d767062b1c461

✅ Data Stored | PKG7681 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: 361df6820a4908e8914c06f4f8bccf339ebf29c08923434884610411cd54b867
✅ Data Stored | PKG7681 | Type: Status | Value: Delay | Txn Hash: bfbcb04d0690e0a10a6ec5692793277e0c4c095611237297c7bdd7195e61ed38

✅ Data Stored | PKG7681 | Type: Temperature | Value: 12.5°C | Txn Hash: 43eba1713964d78415a321519d84806f1fbe9e2af6f1e84e591388d900e1c071
✅ Data Stored | PKG7681 | Type: Humidity | Value: 66% | Txn Hash: e06941c5037c7c5877d57529acebc6f926888efbdf9855082b1e9c29935ac7af

✅ Data Stored | PKG2083 | Type: Location | Value: Yokohama Sales Office | Txn Hash: e59e171e34920475ce4adfa2c6d0e357c1d1130f7121e5fe09676676dbd367c3
✅ Data Stored | PKG2083 | Type: Status | Value: Storage | Txn Hash: bbd2fb6b95a05e69761b608ef86cf5334cd676a43d50c50a64e085e98ad04eb6
✅ Data Stored | PKG2083 | Type: Temperature | Value: 1.5°C | Txn Hash: eaf08c0832c0f3e9bfef80bd46277c9f1896e435853cb33bd6125e223098d3f0

✅ Data Stored | PKG2083 | Type: Humidity | Value: 63% | Txn Hash: b0a982f15d1ed00b7aec60dc60b00775c92651a2c903fa3bdd4c113a74b038b0
✅ Data Stored | PKG2550 | Type: Location | Value: Naha Central Post Office | Txn Hash: e24d64f50f33f120d995d34379e6fd31c514783357e9a9ac3e93d2223cdcfd18

✅ Data Stored | PKG2550 | Type: Status | Value: Delay | Txn Hash: 8d40523454dd6b7ad9fc1de638ed193ef07b69a80238b140f7a735fbd37f0d48
✅ Data Stored | PKG2550 | Type: Temperature | Value: 11.2°C | Txn Hash: f8964d43efccd77984858ce62190d2ff07d614df787f4770dd6e75a56345295c
✅ Data Stored | PKG2550 | Type: Humidity | Value: 65% | Txn Hash: c51ab4980cd3a5218df9f7c3780c58eaa74b53000f739a95fc36109e4aa2d0f4

✅ Data Stored | PKG8155 | Type: Location | Value: Naha Central Post Office | Txn Hash: b2faf30b72dac69e08538028f97899e4f3a0ceaefb83dcc36bbc0370c8c0e1a8
✅ Data Stored | PKG8155 | Type: Status | Value: Departure Scan | Txn Hash: d6c8382e6c66b83713d326ac8fc86a255a2fd2ab4ee42912020ab012d04f5534
✅ Data Stored | PKG8155 | Type: Temperature | Value: 9.8°C | Txn Hash: d2b0b0b7ffba3a18054069a59b7bb2745439c02b895c04353ace2751cb9d2422

✅ Data Stored | PKG8155 | Type: Humidity | Value: 51% | Txn Hash: ad32e1f7eed373290423c2300a8bd2a1bb20026e596abcf0a0cebecf14252857
✅ Data Stored | PKG2886 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: de5a7392d52f34c2f9120e070db55a7a1413f10362c4c9d44dd80754ec8070e5

✅ Data Stored | PKG2886 | Type: Status | Value: Returned | Txn Hash: db1edb8d6dc0ff7dbc25afde714b1d6aca23e285193b308f357d756ed578fee9
✅ Data Stored | PKG2886 | Type: Temperature | Value: 11.7°C | Txn Hash: d46944dc9473b2c2bd1260490be8041c50974f3d28b2a6b8f6eccabc7abcaa91
✅ Data Stored | PKG2886 | Type: Humidity | Value: 35% | Txn Hash: 08376b76a0da76bf035176107fc6c79b2ef3c51ce8d9ab264305c0253dd1b111

✅ Data Stored | PKG1191 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: dfeb434b23d9caf129a2b26e2a9ce543ceca3ba1a5eae819c2133d572c752375
✅ Data Stored | PKG1191 | Type: Status | Value: Storage | Txn Hash: 7fa88a2f4e121da8488ef8959cec2f1740d50dfd0e902576c19bf4fee419461e
✅ Data Stored | PKG1191 | Type: Temperature | Value: -2.0°C | Txn Hash: 959937ff9a04980ee86c8f4fea6fe4a4f99df5dafff099376d96e50fdb8b241b

✅ Data Stored | PKG1191 | Type: Humidity | Value: 74% | Txn Hash: 91038284bbc7fbfd6a4a3bfbaabd6763a1c96af772d19a970ecc714d1fce744f
✅ Data Stored | PKG9613 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: 7ef0e732ec34b54e5ef5f1e605419a1bbaf75383d8a16e54cf7cf21ea1db2344

✅ Data Stored | PKG9613 | Type: Status | Value: Hold at Yamato | Txn Hash: ed36304f51f203ac8fc5bd9b3bfbae2049351998a46a172626a1d730826fa262
✅ Data Stored | PKG9613 | Type: Temperature | Value: 2.2°C | Txn Hash: ab2fd67e153c0e2a61410ec192d79bdecc42705efe1460932efe4ccdbbf357ea
✅ Data Stored | PKG9613 | Type: Humidity | Value: 72% | Txn Hash: f216ae04d14048fa656c6e56d870576a5df9a18815e77bbffcf5ea26a5327c44

✅ Data Stored | PKG8059 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: 53845f9b614d5748e2dfdd22d15777ab4c21fd5d2a0a9ce613a39169d4482878
✅ Data Stored | PKG8059 | Type: Status | Value: Out for Delivery | Txn Hash: be5e9b4ebd2b862e9f96f19f293abfa557333e6243de0ad2c2fd4d35e2891652
✅ Data Stored | PKG8059 | Type: Temperature | Value: -1.1°C | Txn Hash: 9ac8731b0c3007113e0923e0dc177cbfbdc208c6972e122a17f1523cdccbe5fb

✅ Data Stored | PKG8059 | Type: Humidity | Value: 72% | Txn Hash: 3f8b52f1ae9a6a8f7cca04bc8d7f2369a649914220f8e4f69236c9b5df8a4be4
✅ Data Stored | PKG7953 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: 3b2eee7adddfd686acfd1c4562973fb2f537fcc2dd6e0327e5acdb0fe05e9ab2

✅ Data Stored | PKG7953 | Type: Status | Value: Arrival | Txn Hash: e928f6572373755b20312c63bf1f0a30b6a5b9e40d44fb8d24d46cdd0a13f857
✅ Data Stored | PKG7953 | Type: Temperature | Value: 10.8°C | Txn Hash: a04bd7c51cc0791bdd586a6a604b28b9902d8df32360e6e1b1cafa7037a57e79
✅ Data Stored | PKG7953 | Type: Humidity | Value: 62% | Txn Hash: 72658a84ab42c54fff4a0b6d303ddb2a1793dc48fa80e8e6d2d005a374a85030

✅ Data Stored | PKG2989 | Type: Location | Value: Yokohama Sales Office | Txn Hash: c28eb1b449680b25f298679eeaa9caf92bd8b3c8769ae0f2146db43f9ddeed07
✅ Data Stored | PKG2989 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 475c95779294c01fe081ebcd86863c39858ee786b8767d9de67953d6c24e59eb

✅ Data Stored | PKG2989 | Type: Temperature | Value: 1.7°C | Txn Hash: 1e4e521f2480130803136b2a208cdef2dff7c053d55ab95f2492138fe2a6476d
✅ Data Stored | PKG2989 | Type: Humidity | Value: 66% | Txn Hash: f9f69e5aa808fb99106d1b5f3f793739df766c32c110d43a33344fa9fd1dd269

✅ Data Stored | PKG3002 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: f7be6cac4c016302892d25529146ca3a1c1c4fba31fa801dae19544511c4c8d6
✅ Data Stored | PKG3002 | Type: Status | Value: Out for Delivery | Txn Hash: 880fa82da7837b88a22e35d97d0c5ae734c8c0f60fea1e836b2bb37d02f04f0f
✅ Data Stored | PKG3002 | Type: Temperature | Value: 2.0°C | Txn Hash: c23a3cb2c8a9de1e35cdcc5d3599a64c3a38bf60640bfa76b6ba6a2a1f0121fe
✅ Data Stored | PKG3002 | Type: Humidity | Value: 63% | Txn Hash: 2668b4414bfd7b1b2eb17cde3332b96c7421bcac5013b40703aee1d29e18b667

✅ Data Stored | PKG5872 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: 044bc8549a334ed56e3d659c7523b4e2efaf8f2425bac51f1dcc966a0a9af5a1
✅ Data Stored | PKG5872 | Type: Status | Value: Arrival Scan | Txn Hash: 144dd9d0e0ff84be9a5a4813361f9dc1a14ff9b5c5b2f537a3fb7356c28226fe
✅ Data Stored | PKG5872 | Type: Temperature | Value: 9.1°C | Txn Hash: 3f77811100756df5ac525905f69ff1f267aa69b58f05ed7f3fc6a386f5b9d8c7

✅ Data Stored | PKG5872 | Type: Humidity | Value: 82% | Txn Hash: 8feab322bfde22bb5a94a0b064eb55839747ff4cfaa889e09941e52935d6da85
✅ Data Stored | PKG8631 | Type: Location | Value: Naha Central Post Office | Txn Hash: 3f7c1b1f5a4df7ea4bcaf1a37f696c947a66ec61c4439016c50ad9b4bd8d8853

✅ Data Stored | PKG8631 | Type: Status | Value: Returned to the sender | Txn Hash: 210c72d5761808ab47435ed3823d0e6bc82bef10b10bd847e1cab59199fdb24c
✅ Data Stored | PKG8631 | Type: Temperature | Value: 19.8°C | Txn Hash: e848aa00e50e38576e14835e1daeaadc3fc718c9eaabb65f231bc04d3a01bb98
✅ Data Stored | PKG8631 | Type: Humidity | Value: 35% | Txn Hash: 91a214036135c453264d05aeb897194cd35bdbd299f001b28b037884dc33f906

✅ Data Stored | PKG1689 | Type: Location | Value: Osaka Central Post Office | Txn Hash: fdf8c41f60e2da37c5633a21ef5dca4f4b61b716091d56a548315e32dfe2f4b4
✅ Data Stored | PKG1689 | Type: Status | Value: Arrival Scan | Txn Hash: 8781d04bbe987740fb172b108fdae702aa52ffaa928ee847f63eeea8cec94a0e
✅ Data Stored | PKG1689 | Type: Temperature | Value: -2.5°C | Txn Hash: 1eec4c01792ac895ad19f170b9c901f06630dc838fc6bc73135a2fd141f8eedf
✅ Data Stored | PKG1689 | Type: Humidity | Value: 77% | Txn Hash: 3764eaed72241e07244a1577ec0ee1739432879e45a772ab8f517291a39604ab

✅ Data Stored | PKG3400 | Type: Location | Value: Osaka Central Post Office | Txn Hash: 3cf4a469e5fddff641a66e392b4cdd3c9e6445771916d00d32059c180d9feaed
✅ Data Stored | PKG3400 | Type: Status | Value: Hand it over at the window | Txn Hash: 7946c8b78591c26d60f19bbda3a16ccc699f3d726c85e70e22911be1151375b6
✅ Data Stored | PKG3400 | Type: Temperature | Value: -0.2°C | Txn Hash: ac883d2059dc656db66ee631ac7a71e9e672ea9da37d9c162b73962bb24324ca
✅ Data Stored | PKG3400 | Type: Humidity | Value: 63% | Txn Hash: 61f4ac5a0004ebed2dab52091459a8d4718ef2c3349091b487d31332193cfc7e

✅ Data Stored | PKG5481 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: ba52446e85bb9ea427c1ac80e11adeadbf9d1eee790020d9e12f216d1797b0af
✅ Data Stored | PKG5481 | Type: Status | Value: Delivered to the delivery address | Txn Hash: 656bedc1515d03011b5519f01870c808157be140632d37a7eb338de167ffbeb4
✅ Data Stored | PKG5481 | Type: Temperature | Value: 19.6°C | Txn Hash: ad1f02ea0fb649c890f925c2087160caa0edfb86f5b7254e9b70d7777e883bcc
✅ Data Stored | PKG5481 | Type: Humidity | Value: 78% | Txn Hash: 5da1d226eeb581fed3d6f58942bee7858a4cd2f835aa85109a8360fb9ab07ecd

✅ Data Stored | PKG7973 | Type: Location | Value: Naha Central Post Office | Txn Hash: fccc29f6a2ffb913545bd98ed65ba9a8c0721e5f2450e890c528a35c29b09a27
✅ Data Stored | PKG7973 | Type: Status | Value: Arrival Scan | Txn Hash: a588a33e9ce11a7695fadea7b8fb637c4c481b855387ba00d3b4c98ed0415155
✅ Data Stored | PKG7973 | Type: Temperature | Value: -1.8°C | Txn Hash: 6c59ba19fef9d371f935e25347e6a0b149d1047050216041a38e506ff61b4b01
✅ Data Stored | PKG7973 | Type: Humidity | Value: 66% | Txn Hash: 2ca28db9fb6d18f7bcc45c9be449b4b4400734144c46693a94c974ab98e3cb1d

✅ Data Stored | PKG5863 | Type: Location | Value: Naha Central Post Office | Txn Hash: 1ab81d0348b96847b46b588ac53266fde1db47b650abdb6bf6269835f1903e05
✅ Data Stored | PKG5863 | Type: Status | Value: Hand it over at the window | Txn Hash: 51cc15c7b812387b173f1685f0cdc796b7b7b50b3d5ce758063b726d5116f7a4
✅ Data Stored | PKG5863 | Type: Temperature | Value: 3.4°C | Txn Hash: f27e3ff347bf0146a463504e4d27c316581f877bb9c8b04ebce7268925f7c2e3

✅ Data Stored | PKG5863 | Type: Humidity | Value: 62% | Txn Hash: 0544e0096b4779394ad0ee81b2b4cc38bb7cbe4ae49fbc83612de14ba0f1ca11

✅ Data Stored | PKG3928 | Type: Location | Value: Naha Central Post Office | Txn Hash: cdcf919017f71c311070bff0ccff136d65623977d0b6a61a29c7ab721c5d870a
✅ Data Stored | PKG3928 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 92a984f55d9aa6aea8d92ed563c2a8aa66e320e871939aeaf51a1b0a4d7c3f8f
✅ Data Stored | PKG3928 | Type: Temperature | Value: 7.7°C | Txn Hash: 8c2a7bcbbabb18a56c682fe2ad4a613f4a141755d6a059f8abbaaa6d9f30bf32
✅ Data Stored | PKG3928 | Type: Humidity | Value: 87% | Txn Hash: 51ce29981c4418896cf6e449c91218594cd20b2738b58b62a95dd8178f2c670b

✅ Data Stored | PKG8254 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: a46626173165488490a9721121022e058f4e6011475ad68e5e970c7e4e8f7d3c
✅ Data Stored | PKG8254 | Type: Status | Value: Delivered to the delivery address | Txn Hash: 5d7aadf90b9d62e50d790c1a4cbcd97cb8b63ae0702c2456f59f5e32b0585fb4
✅ Data Stored | PKG8254 | Type: Temperature | Value: 11.1°C | Txn Hash: da2b408cef0fe2e29b66f26ed802c06cdefbc162c2ed81d418a5b76d3c533d5f
✅ Data Stored | PKG8254 | Type: Humidity | Value: 44% | Txn Hash: c343b88c9e5ce86a2a459dabd05a86289ffc7da209f9a93bdf65496f17455307

✅ Data Stored | PKG4344 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: f847f1647f13e16c5d108a730c3e90251d3a9c84e4f195cebfed24d66d4e33c3
✅ Data Stored | PKG4344 | Type: Status | Value: Returned | Txn Hash: d0b8130c6020a91fcba169f2c8bda8a27fcded581bf00c5b8850340509980a7e
✅ Data Stored | PKG4344 | Type: Temperature | Value: 3.2°C | Txn Hash: b2b12e24a1cefcbded2409076fc7f10d65517ea3f58cebca93ec732c885d7cb6

✅ Data Stored | PKG4344 | Type: Humidity | Value: 78% | Txn Hash: 80660f8d42f4bdc75bbd758719c21572a0fda946099eeb693ecac2213b05e721
✅ Data Stored | PKG9080 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: c526ec6be3ab7d13d6798805ea765d35ea4ebb366b5734e70bfe03315f33ef09

✅ Data Stored | PKG9080 | Type: Status | Value: Returned to the sender | Txn Hash: ffa6afc305beef5fec1473d915aa1b8f01f7620df171638871699609bff96bac
✅ Data Stored | PKG9080 | Type: Temperature | Value: 8.0°C | Txn Hash: ab0b258ca4f559dce183b25a27064fce44d5a64ee571b5511af477afc6c2ea4d
✅ Data Stored | PKG9080 | Type: Humidity | Value: 68% | Txn Hash: 193dc0aaec1fe247c5ca0b1d1eac8d9ca48daa134aab2c6a220e9d785f58f8d8

✅ Data Stored | PKG7455 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: 43c4d4daaa5577a37195f6adfe901e09938bbc4bf1a5aa74628703a647cb3b5f
✅ Data Stored | PKG7455 | Type: Status | Value: Delivered | Txn Hash: 1b2bf1b59bb5d855f4a443a30a0c1cc5e998e578f6661b283805a67108d4bf67
✅ Data Stored | PKG7455 | Type: Temperature | Value: 7.2°C | Txn Hash: 73bda8011b1c5dbb48f8eee832fc4f08d44c10d1c10593c34846677fc596ffa6
✅ Data Stored | PKG7455 | Type: Humidity | Value: 33% | Txn Hash: 17ae18cd1a47f0255fa0288ec071c72e3c7f6393be49babcb5f5aa4f427b3d6c

✅ Data Stored | PKG8002 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: 0703795f08bf8705ed57af1f5486dcc1ec6e62cb8c7ab596d7b10d9217f07525
✅ Data Stored | PKG8002 | Type: Status | Value: Bring it back due to your absence | Txn Hash: ea324183749d0b3b55a5676e1be3e8ae0cecf6a0b51bfdacfdfb4fc9f737db01
✅ Data Stored | PKG8002 | Type: Temperature | Value: -1.5°C | Txn Hash: b699363e93b246573ed110911b6f27dee0032ee70a4d010a887500c3567c2646
✅ Data Stored | PKG8002 | Type: Humidity | Value: 69% | Txn Hash: 885f1ee5be2c143894d5dd4ddc8ee44645ed27398de8bee023fd19c96627b298

✅ Data Stored | PKG6155 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 939a16ae48f989ea16a7a9d39facf7e8cd7d8c3249a8f5d727c388374ce12df5
✅ Data Stored | PKG6155 | Type: Status | Value: Returned to the sender | Txn Hash: 6002e9554243b3c9832ed44eacff1a18e219f4ea48641416eda8bf93d0da9c7d
✅ Data Stored | PKG6155 | Type: Temperature | Value: 2.8°C | Txn Hash: b7b6e4ac5b3a324b403df9b22377c8a33cf5e1317ad3bee1a9a24278964f7b4b

✅ Data Stored | PKG6155 | Type: Humidity | Value: 77% | Txn Hash: a2a4b6d7cd53f66f1a51d82069836b2e0810b657b714a726416b96d32d443e7f
✅ Data Stored | PKG6108 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: 232b4dfecbcd308eba4528f4c07bb1b875d4f389157edf8388a469a54b917873

✅ Data Stored | PKG6108 | Type: Status | Value: Hold at Yamato | Txn Hash: e9715aa024dc81d10f76f3813cc4c19f5f6f1c43c285660c759e6593d501b0bb
✅ Data Stored | PKG6108 | Type: Temperature | Value: -1.3°C | Txn Hash: 3f5778898923451cb4f0e4a00646cbd28dc19488c7bc8d5c81a43e1f8e5695fe
✅ Data Stored | PKG6108 | Type: Humidity | Value: 86% | Txn Hash: b1913a31f9fa526d5da05e3cbcf387576fff469f99ccb5e80b2b6858b95f275a

✅ Data Stored | PKG2439 | Type: Location | Value: Yokohama Sales Office | Txn Hash: 3adc389548fb210f8fa210e914577c88198668579fdea7d9273febdd0b269f53
✅ Data Stored | PKG2439 | Type: Status | Value: In Transit | Txn Hash: 0c685731631bb01604c463b540c72957a45289a65638966b33d7475279964087
✅ Data Stored | PKG2439 | Type: Temperature | Value: 9.8°C | Txn Hash: 079f6bd3d58b3e90feec554a942b2134aa5d6d3a0c22b44722b4de727fd05d93
✅ Data Stored | PKG2439 | Type: Humidity | Value: 76% | Txn Hash: f62aa8f6b283c346b1e872f72a30d78a7b8058806e4b548553c965a95dd9ab0a

✅ Data Stored | PKG3231 | Type: Location | Value: Naha Central Post Office | Txn Hash: ffc8ba86dd90cc796fe392cec8dd79337dc0ec6bbdfd58ccec0f171b9405d57e
✅ Data Stored | PKG3231 | Type: Status | Value: Hand it over at the window | Txn Hash: 489f9ea16c996a05fd0afd4a6904e0d8093fa10c6b8db3f13c3bcdb9597c158c
✅ Data Stored | PKG3231 | Type: Temperature | Value: 14.6°C | Txn Hash: 685fba5c1642eba6dee75eb30a430a34437c30a6ad19fd5ca61862e3f39a259d
✅ Data Stored | PKG3231 | Type: Humidity | Value: 71% | Txn Hash: 37e051754326becbdbf940bad692305aeb323cc032d2b320851c6fd7d64a94ef

✅ Data Stored | PKG3309 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 6378accd10777d7d1a3f7047ff39093ad4c528d5a482648411f332cdcc7a2271
✅ Data Stored | PKG3309 | Type: Status | Value: Returned | Txn Hash: 020c74c690b24c9d5b22077dcf45ef5724a49a5c6c1b4fea188835fd15417ca4
✅ Data Stored | PKG3309 | Type: Temperature | Value: 0.6°C | Txn Hash: 19a6d71d01e5d06282409d7278f0f879f334d0df20bb3d5d9d1b97d56cd41d0d
✅ Data Stored | PKG3309 | Type: Humidity | Value: 47% | Txn Hash: e42ce07769fe54b5727c88ac86cce833115ee66fdb6f9db943ca503df2388db8

✅ Data Stored | PKG9257 | Type: Location | Value: Yokohama Sales Office | Txn Hash: 739296b9136907f24a803eb5800c6f776d23eea1448d16b2cdf232066c129e39
✅ Data Stored | PKG9257 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 898605c9db1934156e31463fe10069510a734183f5a1cc56d6ef3e87a9dd8540
✅ Data Stored | PKG9257 | Type: Temperature | Value: 8.1°C | Txn Hash: 78188d5d328ffb4f7168e43f59c3ea4057fa2a6620fcf2eb771c94fa141d469a

✅ Data Stored | PKG9257 | Type: Humidity | Value: 76% | Txn Hash: cb154f0a330ff168933d3b8f8e0df838b9f5b10f0a8f86239fe96c03c75903c7
✅ Data Stored | PKG1329 | Type: Location | Value: Osaka Central Post Office | Txn Hash: 2424df5305338546d7e86746944511f3d763ef593580bc9e86725f8b96e63173

✅ Data Stored | PKG1329 | Type: Status | Value: In Transit | Txn Hash: 569775f3f93cccafa6dec80176e3c4ce8d39e1fd0d797014b701c8d404e92e6e
✅ Data Stored | PKG1329 | Type: Temperature | Value: 7.9°C | Txn Hash: a64c03ca8f9a22a6dbabd1b5ff835d41ad464cf05564399537479d59a35a3cec
✅ Data Stored | PKG1329 | Type: Humidity | Value: 80% | Txn Hash: 8026dac04bea286b14d9b96923aee0eff246422b8a4486a90c7dd6b358426f87

✅ Data Stored | PKG6811 | Type: Location | Value: Osaka Central Post Office | Txn Hash: e62001749fbb4576838b4bb0b278c217ce06d3427c808a0e9090e333ba8ec84b
✅ Data Stored | PKG6811 | Type: Status | Value: Hold at Yamato | Txn Hash: 1f59b385f9ade2a75af20f46d2ad759996e78e0591e67d832d00af35dfc671b3
✅ Data Stored | PKG6811 | Type: Temperature | Value: 10.9°C | Txn Hash: e9ae65485c9f15fffcc90c0552c9459336c63514dc3a2daa3898a54b0f43967e

✅ Data Stored | PKG6811 | Type: Humidity | Value: 75% | Txn Hash: a42b28858ee7673b997770f24cf3cac2256e0f2b52877f6112cee0f931782e3c
✅ Data Stored | PKG9244 | Type: Location | Value: Naha Central Post Office | Txn Hash: daa9aee7ea1d7c80f77fcf7101986228c982822956592a69846ff60588de1906

✅ Data Stored | PKG9244 | Type: Status | Value: Returned to the sender | Txn Hash: 59eab4bcc26a4d79a5f7937cbfa387c70535c3d623024c6f613a4f0f77d58659
✅ Data Stored | PKG9244 | Type: Temperature | Value: 20.1°C | Txn Hash: 662cd2dbf1e352438535b5d29c02ae254c202621bc11f9d05191e2a4594fe0b7
✅ Data Stored | PKG9244 | Type: Humidity | Value: 34% | Txn Hash: b420d05fe89e9a143f8a26e3a07de8d25a1d7534de281f655de82e766089e27d

✅ Data Stored | PKG1717 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: 2f30bead56557b5b7e8ed5869da59af9a3d3abc71b53fea077266763c869d100
✅ Data Stored | PKG1717 | Type: Status | Value: Arrival | Txn Hash: 6bfbe2e5cdebaa8eb7fadac710b38ffcae39518104d5841aeb72006660678407
✅ Data Stored | PKG1717 | Type: Temperature | Value: -4.6°C | Txn Hash: 7a0aff4b0a68ea8f9dca40949465c16b10d9960eecf711d544afca190d5b47a7
✅ Data Stored | PKG1717 | Type: Humidity | Value: 47% | Txn Hash: c1e70852544f0959e84b92d3bb4f16fe47977eab135374290a29670a9d47d8e5

✅ Data Stored | PKG3405 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 9d8165fd42db77fcbe13278b6379ffe3fa560705ac2b3847ee1089afb234a065
✅ Data Stored | PKG3405 | Type: Status | Value: Under Investigation | Txn Hash: e919080d924d87bf625023223ce5e51f99932d8ceaa9034c5004d1f517d313fd
✅ Data Stored | PKG3405 | Type: Temperature | Value: 7.7°C | Txn Hash: 60180f1011dbafe32636269118f8bdff7720c17c13421e979397b147b123ac6a
✅ Data Stored | PKG3405 | Type: Humidity | Value: 49% | Txn Hash: 78f867bea016bc797e9638864ab1abd29f0173464fed09f868ca339fc96a639b

✅ Data Stored | PKG4781 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: 8c26a84e4afcb68303b76e0982b4f460100a3c5a1c4083505917931e57aab355
✅ Data Stored | PKG4781 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 6db20beb8c17fa90d658386579076d14869b63cb318bc6399ae9f4df5348639e
✅ Data Stored | PKG4781 | Type: Temperature | Value: 21.1°C | Txn Hash: c56e2587e647b83aeddc94bce2adfaf062795093cc9bf1db92259b8610345201

✅ Data Stored | PKG4781 | Type: Humidity | Value: 53% | Txn Hash: 02739ab727ef31ff8cdd129171c08569145fce162ae31dd81657c4290f7d7720
✅ Data Stored | PKG9294 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 457851f1e8cb952672d59f70fb62c8c311cfb6804628c659d9cee842ed811bba
✅ Data Stored | PKG9294 | Type: Status | Value: Hand it over at the window | Txn Hash: 6a7efb1c3d3cdfb24ea5c563361f4a817cd6bbe140562f70f7f35f8e09454f99

✅ Data Stored | PKG9294 | Type: Temperature | Value: 6.9°C | Txn Hash: 578eff0d8ae1117a78e7f8a7a504d7f954feb94b0c145a6e98aa41245de4e176
✅ Data Stored | PKG9294 | Type: Humidity | Value: 36% | Txn Hash: c2a6b05841c3ab4e1ab000eabb5887d937bbdfe4fa37dad0239cb55588545fa6
✅ Data Stored | PKG2894 | Type: Location | Value: Naha Central Post Office | Txn Hash: 13fa84aeb9fab4ccd80b474776f6d96ba0e9ad89d04800c3e86ddb9dcccdc580

✅ Data Stored | PKG2894 | Type: Status | Value: Hand it over at the window | Txn Hash: 255d11c12e977656f8297dc240683dd7ed1d49c0f605cba7c2758be13529f6f3
✅ Data Stored | PKG2894 | Type: Temperature | Value: 3.7°C | Txn Hash: a9c75a4261fe9e63c6948b3ad21f9d06007ba4b59919156e7bdcbb1f13f02bfd
✅ Data Stored | PKG2894 | Type: Humidity | Value: 34% | Txn Hash: 9880af8af76ef10ccd3cee15ab9b30041a6e04a6e46b552dbf3a1d20669b2e3e

✅ Data Stored | PKG9355 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: 8b32deeef444065c606e24fcb017873ce20167ce5cc4e94abb4f43b7e9dfdad8
✅ Data Stored | PKG9355 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 04c91ffa10a1a59156a7cde5fe396204c90b974735beaa9f707758c735ba9542
✅ Data Stored | PKG9355 | Type: Temperature | Value: 4.0°C | Txn Hash: c6e4b51a9137cc051bc132904506fc67bfafbe970868e0efc87cc1a945b6d001

✅ Data Stored | PKG9355 | Type: Humidity | Value: 70% | Txn Hash: cc46b795618497c98643f96ef8518ddd1fa229418b495575eba8bbcbb266eb50
✅ Data Stored | PKG8480 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: ce3fd519f1d8106f5fada0e4003b5306a696fadad97c5c2bd4b28fb42859b0f0

✅ Data Stored | PKG8480 | Type: Status | Value: Storage | Txn Hash: 1d00234e8ad8ad9ff215572b5048145f36ac916a65386fcd30f18b2c660136ab
✅ Data Stored | PKG8480 | Type: Temperature | Value: 9.9°C | Txn Hash: 20f644fcafe22f93076396f8c0e4d381166e3135b430fbe9fe2bea0467ba0535
✅ Data Stored | PKG8480 | Type: Humidity | Value: 50% | Txn Hash: b2c0f83bf74fb0c34a5d95a95abc55115c02ca3629b2c46553f2acb1620679ee

✅ Data Stored | PKG6235 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: 9222df63a664e93d41b55579b39b8db1598a7c0fa97974693041badc42c47e00
✅ Data Stored | PKG6235 | Type: Status | Value: Arrival | Txn Hash: 7c46224b73dbb2f7da81b24cb5026ae40ef80cfec2a930369003ebc209dad042
✅ Data Stored | PKG6235 | Type: Temperature | Value: 17.1°C | Txn Hash: 2c36a22ccec34bcce904469519227d1a4f6231636a3f3e7d5f8ac877454a0b8c
✅ Data Stored | PKG6235 | Type: Humidity | Value: 71% | Txn Hash: 6ab54e0e35f216d950ac5956e1d8af3913f4b74d781651fc527ec3bdd561f68f

✅ Data Stored | PKG3962 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: c40f419859608f64b6cfe116bf064402e59f97567be2d92815c7d76e88bd09bb
✅ Data Stored | PKG3962 | Type: Status | Value: Returned to the sender | Txn Hash: babbf459e36cdf1c42d49de17a76147ef780b622deedd2eb7b5e5c16b4223a68
✅ Data Stored | PKG3962 | Type: Temperature | Value: 16.5°C | Txn Hash: d0b3ae9fd65d9a78d3ce1af0e50d196714b3ec00dd581cd07dab3ecdc0c1c753

✅ Data Stored | PKG3962 | Type: Humidity | Value: 51% | Txn Hash: d3acc0ade89718f4ef351dadcd8b92493bcfcb6e7c08940f268e4aacda0c5c63
✅ Data Stored | PKG5645 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: 39ff230fa0d5a86a8f80b4b5a6a3077c7cdea82c888b289f516331fa552995b2
✅ Data Stored | PKG5645 | Type: Status | Value: Delay | Txn Hash: 5e6d39dc91b57f5467cfafd1dea50ab57e9b8dd18cbed0785060b9bde555a7a4

✅ Data Stored | PKG5645 | Type: Temperature | Value: 13.9°C | Txn Hash: 13a541d058e81b4bce7da8d1bf420f924a52ba0a0701f908f37b79ab194dbe8b
✅ Data Stored | PKG5645 | Type: Humidity | Value: 77% | Txn Hash: c51c00c806d1210904e54f4a351d5f50f1cd2795f5453c6c72d1c32e10bd09f8

✅ Data Stored | PKG7297 | Type: Location | Value: Osaka Central Post Office | Txn Hash: 8d5b2f356bedd30f48f45847ffe50f3329d7b0d5d461fb82fcc2ab36d29c5b71
✅ Data Stored | PKG7297 | Type: Status | Value: Arrival Scan | Txn Hash: a1616b8d524ba61934aec40a19b35f5b5d352cbe29ebd7b3ec1b607dfd47c863
✅ Data Stored | PKG7297 | Type: Temperature | Value: 16.4°C | Txn Hash: 38bc7db02daac1089ed5cd03700cefa38b20016fe8d4c638f959d540a7f40257
✅ Data Stored | PKG7297 | Type: Humidity | Value: 69% | Txn Hash: ce30d28a216dd4011a87920085393173d29313abf8a094944f1b10ff07c114c7

✅ Data Stored | PKG3700 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: 33dfe6a29cfe9e15ac67e9ff67620b12c58240da7b3b849b25638cbcf8279220
✅ Data Stored | PKG3700 | Type: Status | Value: Hold at Yamato | Txn Hash: 1eb62db820d47ed40d17883d2fc1173796365ecfd77248c9b16fc8c5792454f2
✅ Data Stored | PKG3700 | Type: Temperature | Value: 15.6°C | Txn Hash: 75e8039e6ce719b9e84f0ba15347a3c50880223a15224789a189d301e3c898b3
✅ Data Stored | PKG3700 | Type: Humidity | Value: 55% | Txn Hash: b93c1dfc5947231d40e72e34f08d520c3e44a2e89bd654ed1900fe8f5f31c205

✅ Data Stored | PKG2183 | Type: Location | Value: Osaka Central Post Office | Txn Hash: 1709f0100ac2bcd5d3a99895a4ff563f26610a2625d412a3505076f3714d226e
✅ Data Stored | PKG2183 | Type: Status | Value: Delay | Txn Hash: 3947dd6bc9317539ddb45a55318191b72bc92641073f089babf2d160a78a30b6
✅ Data Stored | PKG2183 | Type: Temperature | Value: 24.5°C | Txn Hash: b4fcfba36df704af0bf6b51afd974bf3b9fddb52f41034a9b0a0080b4b6ccfd1
✅ Data Stored | PKG2183 | Type: Humidity | Value: 35% | Txn Hash: 40573aae2909ad1c8f9dda820e951b6167c7070ec4533a842cc13c479e31bdb5

✅ Data Stored | PKG2282 | Type: Location | Value: Fukuoka Distribution Center | Txn Hash: 6a9d368a45b002eee3ed6f283e8dc8e38906e0f88c52b75132b67e801d38bd06
✅ Data Stored | PKG2282 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 08bf5ff7a42e38e0742a60d33fac9939f33673e4ad8db2ee194a540706e25d84
✅ Data Stored | PKG2282 | Type: Temperature | Value: 5.1°C | Txn Hash: 3b51a60e4f609880aa9f583110aec690918b08001e479c2ea6d39ea416b28525
✅ Data Stored | PKG2282 | Type: Humidity | Value: 30% | Txn Hash: c33cb2e076abfa81b74bf16928212ab3c957e0d986271aa92bf908f27eb9d127

✅ Data Stored | PKG7489 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: 06ae95f187287ec1875e509e281be15b48b66fef944841b3755ed40bca573878
✅ Data Stored | PKG7489 | Type: Status | Value: Returned | Txn Hash: 61b0facae90318dea955e12c2d5b63fc7ae32df60c86df5d51d1abfbce70b88c
✅ Data Stored | PKG7489 | Type: Temperature | Value: 3.7°C | Txn Hash: ee9245094e0bcceb764374c427e61c95abe7c54ae88564472cf36c561c99c0b4
✅ Data Stored | PKG7489 | Type: Humidity | Value: 50% | Txn Hash: 39558c93a9190f62a1cb331c89fd87b7c388593a956b5b11f7aab364b53c00b9

✅ Data Stored | PKG7532 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: 19d54c0523784c6f04ec8211c6bcf28a8f2edd464e60b5042caed9a933c2cff7
✅ Data Stored | PKG7532 | Type: Status | Value: Under Investigation | Txn Hash: 8a2fbfaa6d9c47be4f451c51eb09fd7dafc6f08f15d27e5d629e583df1805726
✅ Data Stored | PKG7532 | Type: Temperature | Value: 2.0°C | Txn Hash: c3d04774cf7ab1d678478543db73d34cc118882bf484fb7eb8b8fca5f991fb63
✅ Data Stored | PKG7532 | Type: Humidity | Value: 40% | Txn Hash: ade22dbff564c2531b9f5bcf1dc5727d8d44cc6c945f166ccf681de6e0e77069

✅ Data Stored | PKG5334 | Type: Location | Value: Yokohama Sales Office | Txn Hash: 374fc058b89ebfb003c959ca8213316479800ebfee9097ddaa3cbd742fd23311
✅ Data Stored | PKG5334 | Type: Status | Value: Delivered | Txn Hash: 3131cf5a093c65d443822f7e56ea0c6fa42df404eaae8b5b348155517540a952
✅ Data Stored | PKG5334 | Type: Temperature | Value: 10.8°C | Txn Hash: 2b9aa0183442ecb2df48c128324d4ac467d50764fcf6e859c50bec780a3cd425
✅ Data Stored | PKG5334 | Type: Humidity | Value: 51% | Txn Hash: 021cac8a210c1ef974a9d5a36b1b679c81e728bf85441a7dedc9ff089fbab9fd

✅ Data Stored | PKG4377 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 4e82bb893c460b268c2c49b5934bfae430ef5491a89a4166f15c1c69d52b1f4c
✅ Data Stored | PKG4377 | Type: Status | Value: Out for Delivery | Txn Hash: 3fc767ad902a3b6826ded745afeb1a265dbe04186d079e6acde0278169a761d1
✅ Data Stored | PKG4377 | Type: Temperature | Value: 16.3°C | Txn Hash: 4511ba59fb7fbf8e4758f9b746831eac5f0f92d0896ee8235bc524e58a9343fc
✅ Data Stored | PKG4377 | Type: Humidity | Value: 56% | Txn Hash: c72a237a3156a3a4af91785cb16d6c21866d27279fc055e49d4eb6bd6a5684fe

✅ Data Stored | PKG9509 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: b635e862f7748ada42fef9b05823b73262c73b67b9c86e992e0d37d751bd166a
✅ Data Stored | PKG9509 | Type: Status | Value: Out for Delivery | Txn Hash: d934d5514bbcfc5d89fd96dd4a5897fa2e250322c182c963e9924bba49c60d32
✅ Data Stored | PKG9509 | Type: Temperature | Value: 2.8°C | Txn Hash: 932f56acb540764d454f21d86b64f4804d13098680f2400f1699a70bbf1d6add
✅ Data Stored | PKG9509 | Type: Humidity | Value: 43% | Txn Hash: 38a457bbe2c8828e620b586e3321597fe5c0550bd584a80db9590059d877bd4f

✅ Data Stored | PKG5718 | Type: Location | Value: Yokohama Sales Office | Txn Hash: 0cf8a636bb75febf6183e835f8982e8996b1f1dee853d75457bcb3ac0590bcd1
✅ Data Stored | PKG5718 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 42d0bdeed08130695c4bd8abeadb0cfd7b05e78e827e552b9d78471a385854e9
✅ Data Stored | PKG5718 | Type: Temperature | Value: 14.3°C | Txn Hash: 57c72c3ef40cd9a7ae9c7419f80e97ecbfe6e5da23d74b9e9bf652c209cfaec4
✅ Data Stored | PKG5718 | Type: Humidity | Value: 51% | Txn Hash: 6509eaddaa036455ea3c702ddc35565c309238634ea4a3ee88acff1186d9d64f

✅ Data Stored | PKG7307 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: 3c16d0200f2bd4f159c27d5ad579e93bca26524c1911fc4c842bb2769d150297
✅ Data Stored | PKG7307 | Type: Status | Value: Delivered to the delivery address | Txn Hash: a8103403983feef8396277a0a63d36aa3c772b8225cde8803ddd270a1d8a1194
✅ Data Stored | PKG7307 | Type: Temperature | Value: 20.0°C | Txn Hash: be50fa299898ddd88575044be53071f282dda0dfcf04a475d5755b1b5801f0c7
✅ Data Stored | PKG7307 | Type: Humidity | Value: 43% | Txn Hash: aceda9061227e8fefc2a3b43591806e820ce40598baede7594e8770e84cd9410

✅ Data Stored | PKG6149 | Type: Location | Value: Nagoya Central Post Office | Txn Hash: ff1717ce4a81f0bae27b8e788e03946c499e80855cb6d8d3e48a0fbbaf30df3f
✅ Data Stored | PKG6149 | Type: Status | Value: Bring it back due to your absence | Txn Hash: 5af4cc54eda6c5f63181318522cf4b71f4e943659a52378e9096e7d97f2fc45c
✅ Data Stored | PKG6149 | Type: Temperature | Value: 4.3°C | Txn Hash: f2766007d11e6470ee752c3168b0d9f9b22c04c1a673cc83b102e4d5f4b5de56
✅ Data Stored | PKG6149 | Type: Humidity | Value: 36% | Txn Hash: d689c8aa6a6aec19f88b5f83e8104986f5899bf9533d85d43d3b79b322de1e59

✅ Data Stored | PKG3680 | Type: Location | Value: Yokohama Sales Office | Txn Hash: 10c1d9bf4e40e07df4ab531b1b025e94c03830be751945ae4be09a6fbcba0a28
✅ Data Stored | PKG3680 | Type: Status | Value: Out for Delivery | Txn Hash: 35a44b94422e521ee6cd96ef7b774d22f6f5e967c94ca7411a793a7d1c377010
✅ Data Stored | PKG3680 | Type: Temperature | Value: -4.0°C | Txn Hash: 262e521eb885bf8ed9170110968d2d310d8e432026fd2e6f24abede2dd459e6c
✅ Data Stored | PKG3680 | Type: Humidity | Value: 78% | Txn Hash: 8162745bec5bbd02d29879a00c6b01cf786c83d09c60506d28debe8be8cabebe

✅ Data Stored | PKG8417 | Type: Location | Value: Tokyo Central Post Office | Txn Hash: 1c4d911501946167a693f2eaad25fff94a6fa33db64a5e53cec58fc4b5e8f603
✅ Data Stored | PKG8417 | Type: Status | Value: Returned | Txn Hash: eadf6e2ad1aadbe90f3c7f9a0215e29b6bcae74a3180b1e5584019c400b9b122
✅ Data Stored | PKG8417 | Type: Temperature | Value: 7.6°C | Txn Hash: a51252b33549e672702a1d75827a95bd7c10d65a9c6699056aa04ec0bdd9dd45
✅ Data Stored | PKG8417 | Type: Humidity | Value: 74% | Txn Hash: 5fd179deeceb0e882568665c80655d166a60ca55e8521220866b5876f688731f

✅ Data Stored | PKG3150 | Type: Location | Value: Osaka Central Post Office | Txn Hash: 494edcf43a746b715d4df9905836b8bee6d78676bd0d79724aa6382cba50d99a
✅ Data Stored | PKG3150 | Type: Status | Value: Out for Delivery | Txn Hash: 6240f207d17f92d3a30ccaee071cb21c9a821e2eccd0ef2951daf579aee0bcdc
✅ Data Stored | PKG3150 | Type: Temperature | Value: 20.4°C | Txn Hash: b0003bdac199869bf1f3762b33641631bce58114703642b5a4d3f558173b491c
✅ Data Stored | PKG3150 | Type: Humidity | Value: 53% | Txn Hash: 101df62b2e701ff5e16374cd338015aa14d0caf2604a908b746d951e98c678c9

✅ Data Stored | PKG1198 | Type: Location | Value: Osaka Central Post Office | Txn Hash: ce10f2f036c4a6eb4edec9aa927973b6a64f027a69cdef6d40bdcb0cdd45f0dd
✅ Data Stored | PKG1198 | Type: Status | Value: Hold at Yamato | Txn Hash: c6fbd46b49ed2b7ece0f303ba97ceccaf5034bbe5b73d2a8e4ffb05ccf9bd896
✅ Data Stored | PKG1198 | Type: Temperature | Value: -3.4°C | Txn Hash: 19ceaf961f4d2a593475ba519a80eac8f8a5b4844abc8e66b1784f645df4e30b
✅ Data Stored | PKG1198 | Type: Humidity | Value: 30% | Txn Hash: db091c61d473c31804ba52455298aa3ffa0fdfd4f85d8b9b1d93d3b46d31c9ef

✅ Data Stored | PKG9015 | Type: Location | Value: Yokohama Sales Office | Txn Hash: 17e40db1ab87047d4f9758b83c6c58450a4f06cfae3ad286d5f162fe6d8d4a4e
✅ Data Stored | PKG9015 | Type: Status | Value: Delay | Txn Hash: a5375de0c8802ec0b1d60685dc02985e41f44ab54a56ce681781243c7a29326e
✅ Data Stored | PKG9015 | Type: Temperature | Value: 12.2°C | Txn Hash: 5ef6884ca31c0286757fc91fb1d40228fcb1c5d1dbfe70ffeea51987c40a2aa6
✅ Data Stored | PKG9015 | Type: Humidity | Value: 78% | Txn Hash: 17f99e5c4dc4179c44d8c35f07eda31cb12361391ac6ede9e5490c4c9ef81d32

✅ Data Stored | PKG7192 | Type: Location | Value: Sapporo Central Post Office | Txn Hash: 6878f0459754f6c66e7238cb6f1bdbe19aca288cf200841c12fcfa2dfe346f3b
✅ Data Stored | PKG7192 | Type: Status | Value: Delivered | Txn Hash: 144438de13c60bc687399fa7b7c7839dc4d91eb169c9671fbe5fd73d64071ad6
✅ Data Stored | PKG7192 | Type: Temperature | Value: 0.5°C | Txn Hash: 82f57a16c71bc5491a69928d346c3b7b97bc61a0b25fbd8c7a2417bece8fa706
✅ Data Stored | PKG7192 | Type: Humidity | Value: 60% | Txn Hash: 600f97d3b73593557c66d937f488dcc2b326f99adb96fbb13d393b84975c47b6

✅ Data Stored | PKG9742 | Type: Location | Value: Naha Central Post Office | Txn Hash: 89f9b917e9568f80a932ce6d8c055b74693c7969091b3b294f7e89a0f167d8df
✅ Data Stored | PKG9742 | Type: Status | Value: Hold at Yamato | Txn Hash: 4f883f02012626efdfd8c9cbee40fe98fb92bb97c1860ab82f5f002bcb56ca5d
✅ Data Stored | PKG9742 | Type: Temperature | Value: -0.5°C | Txn Hash: c259331434b62acc6b75b20f7d050533619557c33d2599f69930af491cf0fb76
✅ Data Stored | PKG9742 | Type: Humidity | Value: 68% | Txn Hash: 7b7f4d87b9dc1e412f3bc4f41e0e027838391e71965858cb7c9cdf23612ec987

✅ Data Stored | PKG7815 | Type: Location | Value: Naha Central Post Office | Txn Hash: 5eb167c63bff877d40cad1c87394b5e7af4b66b46e474e02d42a6d89900e0946
✅ Data Stored | PKG7815 | Type: Status | Value: Returned to the sender | Txn Hash: adabfb3bc4bd0c6efd32f7a6e42d1f4e58488f9c4818d414e14d851fb0523b66
✅ Data Stored | PKG7815 | Type: Temperature | Value: -2.1°C | Txn Hash: ca65edb37f7592ae537c9b681d07fa2aaa78cb1c322aa4b41ae0c1be1984cecd
✅ Data Stored | PKG7815 | Type: Humidity | Value: 39% | Txn Hash: 57642465f7cd93d982c4312a3bc21d8ccbd0137ae1ae48b9d25918a5630a18dc

✅ Data Stored | PKG2329 | Type: Location | Value: Naha Central Post Office | Txn Hash: 8c6f7b278480b14fcdbe1568d2dc579a09a9c78f67099b0d9a95dc1777a5f6d8
✅ Data Stored | PKG2329 | Type: Status | Value: Hold at Yamato | Txn Hash: 5842d534564a980b03d53b1a26b8ae6cffa76b7f23399bfffa06f6c35613c3b2
✅ Data Stored | PKG2329 | Type: Temperature | Value: 4.2°C | Txn Hash: 1c17381f6e085a046fd45d6f76c6077c36b047cc98501b353b6c65d250e113ec
✅ Data Stored | PKG2329 | Type: Humidity | Value: 84% | Txn Hash: f1408154c11134578dbbd17eb26c81469f5b70e917319a90051d66b61d80cee4

✅ Data Stored | PKG6240 | Type: Location | Value: Osaka Central Post Office | Txn Hash: 951a0b5a3066c2697b20afb4c723ea852574b57f1d8f76d2f725a7ce7f1adb03
✅ Data Stored | PKG6240 | Type: Status | Value: Hold at Yamato | Txn Hash: 5ec6506a7fe95b3bcf345a92db54f56b2d44ebde7eb22c278ff32b0734451369
✅ Data Stored | PKG6240 | Type: Temperature | Value: 6.2°C | Txn Hash: 2e3fa49949a4fbfacf454728a6c32fc09d987a5e93ce472aae9d2f26864ae3a6
✅ Data Stored | PKG6240 | Type: Humidity | Value: 61% | Txn Hash: b40151f3ac800b13450c179bf9887ecd9b37299376a882f4d5b44400b3a74472

✅ Data Stored | PKG6957 | Type: Location | Value: Yokohama Sales Office | Txn Hash: ca26275a84f9f0e2f78d5f6e4187a5d6df666fbbbc863d187b17a3238f49c5a2
✅ Data Stored | PKG6957 | Type: Status | Value: Returned to the sender | Txn Hash: 800265f2c2d6ec62fc77c92bb7daa322f209a14e3f1f2dc361e4ab4d84982102
✅ Data Stored | PKG6957 | Type: Temperature | Value: 4.1°C | Txn Hash: 40256a258a4394c771f899ad10646334811371dc74ef01fbd2b966c55a0af420
✅ Data Stored | PKG6957 | Type: Humidity | Value: 58% | Txn Hash: bcf64b269fd410b0a1403dfdea11bc4d48b6e2b876e040876887bd81934505df

✅ Data Stored | PKG3165 | Type: Location | Value: Naha Central Post Office | Txn Hash: 927b3155cafd6a6396c507ac92f6befe7446106bf768f0b4047af82a1723aaa6
✅ Data Stored | PKG3165 | Type: Status | Value: Returned | Txn Hash: e7043998096f9c423a7e4ae5256190e340a5db00dddd87d55299fef8a192fc40
✅ Data Stored | PKG3165 | Type: Temperature | Value: 14.8°C | Txn Hash: 05f26c2d911ae653c9de2e6120171dab0d27c3dcacc77a132772f3d824aa423f
✅ Data Stored | PKG3165 | Type: Humidity | Value: 78% | Txn Hash: 3d958f3e3c94665c59eced1d2645d8ad0d8809d06e2c22f1e0874da579205485

✅ Successfully stored 75 new rows on the blockchain!
ℹ️ Skipped 25 duplicate rows.

In [5]:
current_records = contract.functions.getTotalRecords().call()
print(f"Total IoT records stored: {current_records}")

Total IoT records stored: 400

In [6]:
current_records = contract.functions.getTotalRecords().call()
max_entries = contract.functions.MAX_ENTRIES().call()
remaining_entries = max_entries - current_records

print(f"Current IoT records stored: {current_records}")
print(f"Maximum records allowed: {max_entries}")
print(f"Remaining storage slots: {remaining_entries}")

if remaining_entries == 0:
    print("⚠️ The contract is full. Redeploy a new contract or reset the chain to store more data.")
elif remaining_entries <= 20:
    print("⚠️ The contract is nearing capacity.")

Current IoT records stored: 400
Maximum records allowed: 500
Remaining storage slots: 100

In [7]:
# Retrieve and display the first stored record in aligned format
first_record = contract.functions.getRecord(0).call()
first_package = first_record[1]

# Lookup static details from raw CSV
row = df[df['package_id'] == first_package].iloc[0]

# Query blockchain for all telemetry fields of this package
total_stored = contract.functions.getTotalRecords().call()
pkg_telemetry = {}
for i in range(total_stored):
    rec = contract.functions.getRecord(i).call()
    if rec[1] == first_package:
        pkg_telemetry[rec[2]] = rec[3]

# Extract fields
order_date = row.get('order_date', 'N/A')
delivery_date = row.get('expected_delivery_date', row.get('delivery_date', 'N/A'))
origin = row.get('origin', 'N/A')
current_loc = pkg_telemetry.get('Location', row.get('current_location', 'N/A'))
delivery_loc = row.get('delivery_location', 'N/A')
perishable = row.get('perishable', 'N/A')
temp_str = pkg_telemetry.get('Temperature', f"{row.get('temperature', 0.0)}°C")

# Calculate temperature issue
temp_val = float(row.get('temperature', 0.0))
if str(perishable).strip().lower() == 'yes':
    temp_issue = "Normal" if temp_val <= 8.0 else "Temperature Alert"
else:
    temp_issue = "Not Applicable"

status = pkg_telemetry.get('Status', row.get('latest_status', 'N/A'))

pivoted_first_record = [
    first_record[0],
    first_package,
    order_date,
    delivery_date,
    origin,
    current_loc,
    delivery_loc,
    perishable,
    temp_str,
    temp_issue,
    status
]

print("First Stored Record:", pivoted_first_record)
print("\n📦 First Stored Record")
print(f"Timestamp: {pivoted_first_record[0]}")
print(f"Package ID: {pivoted_first_record[1]}")
print(f"Order Date: {pivoted_first_record[2]}")
print(f"Expected Delivery Date: {pivoted_first_record[3]}")
print(f"Origin: {pivoted_first_record[4]}")
print(f"Location: {pivoted_first_record[5]}")
print(f"Delivery Location: {pivoted_first_record[6]}")
print(f"Perishable: {pivoted_first_record[7]}")
print(f"Temperature: {pivoted_first_record[8]}")
print(f"Temperature Issue: {pivoted_first_record[9]}")
print(f"Status: {pivoted_first_record[10]}")

First Stored Record: [1780658433, 'PKG7545', '2026-04-29 23:26:26.858009', '2026-05-05 23:26:26.858015', 'Tokyo', 'Naha Central Post Office', 'Tokyo', 'No', '10.7°C', 'Not Applicable', 'Out for Delivery']

📦 First Stored Record
Timestamp: 1780658433
Package ID: PKG7545
Order Date: 2026-04-29 23:26:26.858009
Expected Delivery Date: 2026-05-05 23:26:26.858015
Origin: Tokyo
Location: Naha Central Post Office
Delivery Location: Tokyo
Perishable: No
Temperature: 10.7°C
Temperature Issue: Not Applicable
Status: Out for Delivery

In [8]:
# Retrieve first 5 unique packages stored on the blockchain
total_records = contract.functions.getTotalRecords().call()
unique_packages = []
for i in range(total_records):
    rec = contract.functions.getRecord(i).call()
    pkg_id = rec[1]
    # Keep track of unique package IDs along with the timestamp of their first transaction
    if not any(p[1] == pkg_id for p in unique_packages):
        unique_packages.append((rec[0], pkg_id))
    if len(unique_packages) >= 5:
        break

aligned_records = []
for timestamp, pkg_id in unique_packages:
    # Lookup details from CSV
    row = df[df['package_id'] == pkg_id].iloc[0]
    
    # Query blockchain for all telemetry fields of this package
    pkg_telemetry = {}
    for i in range(total_records):
        rec = contract.functions.getRecord(i).call()
        if rec[1] == pkg_id:
            pkg_telemetry[rec[2]] = rec[3]
            
    # Extract fields
    order_date = row.get('order_date', 'N/A')
    delivery_date = row.get('expected_delivery_date', row.get('delivery_date', 'N/A'))
    origin = row.get('origin', 'N/A')
    current_loc = pkg_telemetry.get('Location', row.get('current_location', 'N/A'))
    delivery_loc = row.get('delivery_location', 'N/A')
    perishable = row.get('perishable', 'N/A')
    temp_str = pkg_telemetry.get('Temperature', f"{row.get('temperature', 0.0)}°C")

    # Calculate temperature issue
    temp_val = float(row.get('temperature', 0.0))
    if str(perishable).strip().lower() == 'yes':
        temp_issue = "Normal" if temp_val <= 8.0 else "Temperature Alert"
    else:
        temp_issue = "Not Applicable"

    status = pkg_telemetry.get('Status', row.get('latest_status', 'N/A'))

    aligned_records.append({
        "timestamp": pd.to_datetime(timestamp, unit='s'),
        "package_id": pkg_id,
        "order_date": order_date,
        "expected_delivery_date": delivery_date,
        "origin": origin,
        "current_location": current_loc,
        "delivery_location": delivery_loc,
        "perishable": perishable,
        "temperature": temp_str,
        "temperature_issue": temp_issue,
        "status": status
    })

df_unique_preview = pd.DataFrame(aligned_records)
print(f"First {len(df_unique_preview)} Unique Package Records on Blockchain:")
display(df_unique_preview)

First 5 Unique Package Records on Blockchain:

            timestamp package_id                  order_date      expected_delivery_date   origin             current_location delivery_location perishable temperature temperature_issue                             status
0 2026-06-05 11:20:33    PKG7545  2026-04-29 23:26:26.858009  2026-05-05 23:26:26.858015    Tokyo     Naha Central Post Office             Tokyo         No      10.7°C    Not Applicable                   Out for Delivery
1 2026-06-05 11:20:33    PKG2659  2026-04-28 23:26:26.858141  2026-05-07 23:26:26.858146    Tokyo   Nagoya Central Post Office             Kyoto        Yes       6.2°C            Normal                            Arrival
2 2026-06-05 11:20:33    PKG7965  2026-05-03 23:26:26.858267  2026-05-08 23:26:26.858271    Osaka   Nagoya Central Post Office             Osaka        Yes      -3.1°C            Normal                            Storage
3 2026-06-05 11:20:33    PKG5296  2026-05-03 23:26:26.858370  2026-05-05 23:26:26.858374  Fukuoka  Sapporo Central Post Office           Sapporo        Yes       6.3°C            Normal  Delivered to the delivery address
4 2026-06-05 11:20:33    PKG9987  2026-05-03 23:26:26.858492  2026-05-07 23:26:26.858501  Fukuoka        Yokohama Sales Office           Sapporo         No       0.7°C    Not Applicable  Bring it back due to your absence